# Generated by Django 5.0.4 on 2024-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='lesson_number',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['title'], name='scheduler_c_title_66a462_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['title'], name='scheduler_s_title_3c2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='scheduler_t_full_na_7e3717_idx'),
        ),
    ]
