# Generated by Django 5.0.4 on 2024-12-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.lessontime')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['is_notified'], name='scheduler_l_is_noti_4ff68c_idx')],
                'unique_together': {('group', 'teacher', 'lesson_time')},
            },
        ),
    ]
