# Generated by Django 5.0.4 on 2024-12-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_lessonnotificationqueue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lessonbuffer',
            new_name='scheduler_l_group_i_916aaa_idx',
            old_name='scheduler_l_group_i_74e11c_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonbuffer',
            new_name='scheduler_l_group_i_21c92a_idx',
            old_name='scheduler_l_group_i_76dd8d_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonnotificationqueue',
            new_name='scheduler_l_is_noti_b293cf_idx',
            old_name='scheduler_l_is_noti_4ff68c_idx',
        ),
        migrations.RenameIndex(
            model_name='lessontime',
            new_name='scheduler_l_date_d196af_idx',
            old_name='scheduler_l_date_19db36_idx',
        ),
        migrations.RenameIndex(
            model_name='lessontime',
            new_name='scheduler_l_date_afd8f1_idx',
            old_name='scheduler_l_date_db0bea_idx',
        ),
        migrations.AlterModelTable(
            name='lessonbuffer',
            table='scheduler_lesson_buffer',
        ),
        migrations.AlterModelTable(
            name='lessonnotificationqueue',
            table='scheduler_lesson_notification_queue',
        ),
        migrations.AlterModelTable(
            name='lessontime',
            table='scheduler_lesson_time',
        ),
    ]
