# Generated by Django 5.0.4 on 2024-12-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_rename_scheduler_l_group_i_74e11c_idx_scheduler_l_group_i_916aaa_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('lesson_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'scheduler_period_template',
            },
        ),
        migrations.RenameModel(
            old_name='LessonTime',
            new_name='Period',
        ),
        migrations.DeleteModel(
            name='LessonTimeTemplate',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_99f8bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_fb24ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonbuffer',
            name='scheduler_l_group_i_916aaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonbuffer',
            name='scheduler_l_group_i_21c92a_idx',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='lessonbuffer',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='lessonnotificationqueue',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='scheduler_p_date_e474d4_idx',
            old_name='scheduler_l_date_d196af_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='scheduler_p_date_824543_idx',
            old_name='scheduler_l_date_afd8f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lessonnotificationqueue',
            unique_together={('group', 'teacher', 'period')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'period'], name='scheduler_l_group_i_0be660_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'period', 'subgroup'], name='scheduler_l_group_i_4b97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'period'], name='scheduler_l_group_i_5d815e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'period', 'subgroup'], name='scheduler_l_group_i_a6099c_idx'),
        ),
        migrations.AlterModelTable(
            name='period',
            table=None,
        ),
        migrations.AlterUniqueTogether(
            name='periodtemplate',
            unique_together={('day_of_week', 'lesson_number')},
        ),
    ]
