# Generated by Django 5.0.4 on 2024-12-30 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_convert_day_of_week_to_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtemplate',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='lesson_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='lesson_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelOptions(
            name='periodtemplate',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='periodtemplate',
            unique_together={('lesson_number', 'start_date')},
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='scheduler.periodtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TimingWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='scheduler.timing')),
            ],
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='start_time',
        ),
        migrations.AddConstraint(
            model_name='timing',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='check_timing_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='timingweekday',
            unique_together={('timing', 'day_of_week')},
        ),
    ]
