# Generated by Django 5.0.4 on 2025-01-10 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_periodtemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonnotificationqueue',
            name='scheduler_l_is_noti_b293cf_idx',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='notification_date',
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 10, 14, 19, 53, 106437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
