# Generated by Django 5.0.4 on 2025-02-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_lessonnotificationqueue_scheduler_l_is_noti_b293cf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='scheduler_g_grade_f83891_idx',
        ),
        migrations.RemoveIndex(
            model_name='period',
            name='scheduler_p_date_824543_idx',
        ),
        migrations.RenameField(
            model_name='lessonnotificationqueue',
            old_name='is_notified',
            new_name='is_sent',
        ),
        migrations.AlterUniqueTogether(
            name='lessonnotificationqueue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='data_key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduler.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['title'], name='scheduler_g_title_4c88cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['period'], name='scheduler_l_period__997cb6_idx'),
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='period',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='updated_at',
        ),
    ]
