# Generated by Django 5.1.7 on 2025-03-19 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_remove_group_scheduler_g_grade_f83891_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte')], max_length=20)),
                ('social_id', models.CharField(max_length=50)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='subscription',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_0be660_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_period__997cb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='scheduler_u_telegra_f1ba04_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_lesson_start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_schedule_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['period', 'group'], name='scheduler_l_period__ee16df_idx'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.DeleteModel(
            name='LessonNotificationQueue',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'social_id')},
        ),
    ]
