# Generated by Django 5.1.7 on 2025-03-19 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_socialaccount_user_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
