# Generated by Django 5.1.7 on 2025-04-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_socialaccount_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='provider',
            new_name='platform',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('platform', 'social_id')},
        ),
    ]
