# Generated by Django 5.1.7 on 2025-04-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_rename_provider_socialaccount_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name']},
        ),
    ]
