# Generated by Django 5.1.7 on 2025-05-18 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scheduler', '0018_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['faculty', 'is_active'], name='scheduler_g_faculty_d45436_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['grade', 'is_active'], name='scheduler_g_grade_f1a820_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'social_id'], name='scheduler_s_platfor_a6b7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='scheduler_u_usernam_8d0452_idx'),
        ),
    ]
