# Generated by Django 5.1.7 on 2025-09-18 02:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scheduler", "0019_lesson_updated_at_subscription_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSubscription",
            fields=[
                (
                    "subscription_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scheduler.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("scheduler.subscription",),
        ),
        migrations.CreateModel(
            name="TeacherSubscription",
            fields=[
                (
                    "subscription_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scheduler.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("scheduler.subscription",),
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_user_subscription",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="scheduler_s_content_e8727a_idx",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="object_id",
        ),
        migrations.AddField(
            model_name="faculty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="groupsubscription",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="scheduler.group",
            ),
        ),
        migrations.AddField(
            model_name="teachersubscription",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="scheduler.teacher",
            ),
        ),
    ]
