# Generated by Django 5.1.7 on 2025-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0020_groupsubscription_teachersubscription_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_subscription_per_user'),
        ),
    ]
