# Generated by Django 5.1.7 on 2025-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_remove_user_date_joined_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'user'], name='scheduler_s_platfor_b8c518_idx'),
        ),
    ]
