# Generated by Django 5.1.7 on 2025-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_socialaccount_scheduler_s_platfor_b8c518_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
