# Generated by Django 5.1.7 on 2025-10-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_socialaccount_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
