# Generated by Django 5.1.7 on 2025-11-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0025_socialaccount_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
