# Generated by Django 5.1.7 on 2025-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0026_alter_group_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="link",
        ),
        migrations.AddField(
            model_name="group",
            name="endpoint",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="endpoint",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
