# Generated by Django 5.1.7 on 2025-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0027_remove_group_link_group_endpoint_teacher_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="endpoint",
            field=models.CharField(max_length=128),
        ),
    ]
