# Generated by Django 5.1.7 on 2025-11-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0028_alter_group_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_schedule_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_upcoming_lessons",
            field=models.BooleanField(default=True),
        ),
    ]
