# Generated by Django 5.2.9 on 2026-10-07 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('sheet_names', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheetContent',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParseRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_configuration', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField()),
                ('reference_date', models.DateField()),
                ('knowledge_as_of', models.DateTimeField()),
                ('parser_manifest', models.TextField()),
                ('head_revision', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule_ingestion.schedulesource')),
            ],
        ),
        migrations.CreateModel(
            name='ExportRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('payload', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='schedule_ingestion.parserun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'number'), name='ingestion_export_number'), models.UniqueConstraint(fields=('run', 'request_id'), name='ingestion_export_request'), models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='ingestion_export_positive')],
            },
        ),
        migrations.CreateModel(
            name='RunSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='schedule_ingestion.parserun')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule_ingestion.sheetcontent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'name'), name='ingestion_run_sheet_name'), models.UniqueConstraint(fields=('run', 'position'), name='ingestion_run_sheet_position')],
            },
        ),
    ]
