# Generated by Django 5.2.9 on 2026-10-07 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0002_schedulesource_sheetcontent_parserun_exportrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('export', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule_ingestion.exportrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='schedule_ingestion.parserun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('run',), name='ingestion_one_running_parse')],
            },
        ),
    ]
