# Generated by Django 5.2.9 on 2026-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0003_parseattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserun',
            name='acquisition_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedulesource',
            name='sheet_gids',
            field=models.JSONField(default=dict),
        ),
    ]
