# Generated by Django 5.2.9 on 2026-10-07 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0004_parserun_acquisition_id_schedulesource_sheet_gids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_ids', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automatic', models.BooleanField(default=False)),
                ('requested_by', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('prepared_payload', models.TextField()),
                ('prepared_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule_ingestion.exportrevision')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'applied', 'superseded'])), name='ingestion_publication_status'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ingestion_publication_range')],
            },
        ),
    ]
