# Generated by Django 5.2.9 on 2026-10-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0005_schedulewriteevent_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=16)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('token', models.UUIDField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='schedule_ingestion.publication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'phase'), name='ingestion_delivery_phase'), models.CheckConstraint(condition=models.Q(('phase__in', ['notifications', 'report'])), name='ingestion_delivery_phase_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sending', 'completed', 'uncertain', 'skipped'])), name='ingestion_delivery_status')],
            },
        ),
    ]
