# Generated by Django 5.2.9 on 2026-10-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0006_publicationdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryResolution',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=16)),
                ('actor', models.TextField()),
                ('reason', models.TextField()),
                ('worker_stopped', models.BooleanField(default=False)),
                ('previous', models.JSONField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='schedule_ingestion.publicationdelivery')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('decision__in', ['retry', 'skip'])), name='ingestion_resolution_decision')],
            },
        ),
    ]
