# Generated by Django 5.2.9 on 2026-10-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ingestion', '0007_deliveryresolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrevision',
            options={'permissions': [('review_export', 'Can review a parser export'), ('publish_export', 'Can publish a parser export')]},
        ),
    ]
