# Generated by Django 5.2.9 on 2026-01-19 10:22

import datetime
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# scheduler.migrations.0007_convert_day_of_week_to_numbers

def convert_day_of_week(apps, schema_editor):
    PeriodTemplate = apps.get_model('scheduler', 'PeriodTemplate')

    # Сопоставляем строковые значения с числовыми
    days_of_week_map = {
        'Monday': 0,  # Понедельник
        'Tuesday': 1,  # Вторник
        'Wednesday': 2,  # Среда
        'Thursday': 3,  # Четверг
        'Friday': 4,  # Пятница
        'Saturday': 5,  # Суббота
        'Sunday': 6, # Воскресение
    }

    for template in PeriodTemplate.objects.all():
        # Обновляем строковое значение на числовое
        template.day_of_week = days_of_week_map.get(template.day_of_week, template.day_of_week)
        template.save()



class Migration(migrations.Migration):

    replaces = [('scheduler', '0001_initial'), ('scheduler', '0002_user_email'), ('scheduler', '0003_alter_teacher_managers_and_more'), ('scheduler', '0004_lessonnotificationqueue'), ('scheduler', '0005_rename_scheduler_l_group_i_74e11c_idx_scheduler_l_group_i_916aaa_idx_and_more'), ('scheduler', '0006_periodtemplate_rename_lessontime_period_and_more'), ('scheduler', '0007_convert_day_of_week_to_numbers'), ('scheduler', '0008_alter_periodtemplate_options_and_more'), ('scheduler', '0009_remove_lessonnotificationqueue_scheduler_l_is_noti_b293cf_idx_and_more'), ('scheduler', '0010_remove_group_scheduler_g_grade_f83891_idx_and_more'), ('scheduler', '0011_socialaccount_remove_authtoken_user_and_more'), ('scheduler', '0012_alter_user_id'), ('scheduler', '0013_alter_socialaccount_user_alter_user_date_joined_and_more'), ('scheduler', '0014_alter_socialaccount_user'), ('scheduler', '0015_alter_socialaccount_provider_and_more'), ('scheduler', '0016_rename_provider_socialaccount_platform_and_more'), ('scheduler', '0017_alter_teacher_options'), ('scheduler', '0018_alter_subscription_unique_together_and_more'), ('scheduler', '0019_lesson_updated_at_subscription_updated_at_and_more'), ('scheduler', '0020_groupsubscription_teachersubscription_and_more'), ('scheduler', '0021_subscription_unique_subscription_per_user'), ('scheduler', '0022_remove_user_date_joined_user_created_at_and_more'), ('scheduler', '0023_socialaccount_scheduler_s_platfor_b8c518_idx'), ('scheduler', '0024_socialaccount_is_blocked'), ('scheduler', '0025_socialaccount_chat_id'), ('scheduler', '0026_alter_group_grade'), ('scheduler', '0027_remove_group_link_group_endpoint_teacher_endpoint'), ('scheduler', '0028_alter_group_endpoint'), ('scheduler', '0029_user_notify_schedule_updates_and_more'), ('scheduler', '0030_alter_classroom_options_alter_faculty_options_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, unique=True)),
                ('short_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('subgroup', models.CharField(default='0', max_length=1)),
                ('notify_on_schedule_change', models.BooleanField(default=True)),
                ('notify_on_lesson_start', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='scheduler_f_is_acti_6ee559_idx'), models.Index(fields=['short_title'], name='scheduler_f_short_t_a9bbb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('grade', models.CharField(max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scheduler.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_number', models.CharField(max_length=1)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'lesson_number'], name='scheduler_l_date_19db36_idx'), models.Index(fields=['date'], name='scheduler_l_date_db0bea_idx')],
                'unique_together': {('date', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonTimeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота')], max_length=10)),
                ('lesson_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'unique_together': {('day_of_week', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(default='0', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.classroom')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.lessontime')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(default='0', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.classroom')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.group')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.lessontime')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.teacher')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id', 'is_active'], name='scheduler_u_telegra_f1ba04_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='scheduler_g_is_acti_5ad30c_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['grade', 'title'], name='scheduler_g_grade_f83891_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['content_type', 'object_id'], name='scheduler_s_content_e8727a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'lesson_time'], name='scheduler_l_group_i_916aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'lesson_time', 'subgroup'], name='scheduler_l_group_i_21c92a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'lesson_time'], name='scheduler_l_group_i_99f8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'lesson_time', 'subgroup'], name='scheduler_l_group_i_fb24ce_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='lesson_number',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['title'], name='scheduler_c_title_66a462_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['title'], name='scheduler_s_title_3c2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='scheduler_t_full_na_7e3717_idx'),
        ),
        migrations.CreateModel(
            name='LessonNotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.lessontime')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['is_notified'], name='scheduler_l_is_noti_4ff68c_idx')],
                'unique_together': {('group', 'teacher', 'lesson_time')},
            },
        ),
        migrations.RenameIndex(
            model_name='lessonbuffer',
            new_name='scheduler_l_group_i_916aaa_idx',
            old_name='scheduler_l_group_i_74e11c_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonbuffer',
            new_name='scheduler_l_group_i_21c92a_idx',
            old_name='scheduler_l_group_i_76dd8d_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonnotificationqueue',
            new_name='scheduler_l_is_noti_b293cf_idx',
            old_name='scheduler_l_is_noti_4ff68c_idx',
        ),
        migrations.RenameIndex(
            model_name='lessontime',
            new_name='scheduler_l_date_d196af_idx',
            old_name='scheduler_l_date_19db36_idx',
        ),
        migrations.RenameIndex(
            model_name='lessontime',
            new_name='scheduler_l_date_afd8f1_idx',
            old_name='scheduler_l_date_db0bea_idx',
        ),
        migrations.AlterModelTable(
            name='lessonbuffer',
            table='scheduler_lesson_buffer',
        ),
        migrations.AlterModelTable(
            name='lessonnotificationqueue',
            table='scheduler_lesson_notification_queue',
        ),
        migrations.AlterModelTable(
            name='lessontime',
            table='scheduler_lesson_time',
        ),
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('lesson_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'scheduler_period_template',
            },
        ),
        migrations.RenameModel(
            old_name='LessonTime',
            new_name='Period',
        ),
        migrations.DeleteModel(
            name='LessonTimeTemplate',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_99f8bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_fb24ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonbuffer',
            name='scheduler_l_group_i_916aaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonbuffer',
            name='scheduler_l_group_i_21c92a_idx',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='lessonbuffer',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='lessonnotificationqueue',
            old_name='lesson_time',
            new_name='period',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='scheduler_p_date_e474d4_idx',
            old_name='scheduler_l_date_d196af_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='scheduler_p_date_824543_idx',
            old_name='scheduler_l_date_afd8f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lessonnotificationqueue',
            unique_together={('group', 'teacher', 'period')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'period'], name='scheduler_l_group_i_0be660_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'period', 'subgroup'], name='scheduler_l_group_i_4b97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'period'], name='scheduler_l_group_i_5d815e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'period', 'subgroup'], name='scheduler_l_group_i_a6099c_idx'),
        ),
        migrations.AlterModelTable(
            name='period',
            table=None,
        ),
        migrations.AlterUniqueTogether(
            name='periodtemplate',
            unique_together={('day_of_week', 'lesson_number')},
        ),
        migrations.RunPython(
            code=convert_day_of_week,
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='lesson_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='lesson_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelOptions(
            name='periodtemplate',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='periodtemplate',
            unique_together={('lesson_number', 'start_date')},
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='scheduler.periodtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TimingWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='scheduler.timing')),
            ],
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='periodtemplate',
            name='start_time',
        ),
        migrations.AddConstraint(
            model_name='timing',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_timing_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='timingweekday',
            unique_together={('timing', 'day_of_week')},
        ),
        migrations.RemoveIndex(
            model_name='lessonnotificationqueue',
            name='scheduler_l_is_noti_b293cf_idx',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='notification_date',
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 10, 14, 19, 53, 106437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='scheduler_g_grade_f83891_idx',
        ),
        migrations.RemoveIndex(
            model_name='period',
            name='scheduler_p_date_824543_idx',
        ),
        migrations.RenameField(
            model_name='lessonnotificationqueue',
            old_name='is_notified',
            new_name='is_sent',
        ),
        migrations.AlterUniqueTogether(
            name='lessonnotificationqueue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='data_key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnotificationqueue',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduler.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['title'], name='scheduler_g_title_4c88cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['period'], name='scheduler_l_period__997cb6_idx'),
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='period',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte')], max_length=20)),
                ('social_id', models.CharField(max_length=50)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessonnotificationqueue',
            name='subscription',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_0be660_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_period__997cb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='scheduler_u_telegra_f1ba04_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_lesson_start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_schedule_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['period', 'group'], name='scheduler_l_period__ee16df_idx'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.DeleteModel(
            name='LessonNotificationQueue',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'social_id')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='LessonBuffer',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='provider',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('platform', 'social_id')},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_subscription'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['faculty', 'is_active'], name='scheduler_g_faculty_d45436_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['grade', 'is_active'], name='scheduler_g_grade_f1a820_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'social_id'], name='scheduler_s_platfor_a6b7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='scheduler_u_usernam_8d0452_idx'),
        ),
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('subscription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=('scheduler.subscription',),
        ),
        migrations.CreateModel(
            name='TeacherSubscription',
            fields=[
                ('subscription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=('scheduler.subscription',),
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_subscription',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='scheduler_s_content_e8727a_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='object_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='scheduler.group'),
        ),
        migrations.AddField(
            model_name='teachersubscription',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='scheduler.teacher'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_subscription_per_user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'user'], name='scheduler_s_platfor_b8c518_idx'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='endpoint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='endpoint',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_schedule_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_upcoming_lessons',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='periodtemplate',
            options={'ordering': ['start_date'], 'verbose_name': 'Period Template', 'verbose_name_plural': 'Period Templates'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social Account', 'verbose_name_plural': 'Social Accounts'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
