# Generated by Django 5.0.4 on 2024-05-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id_faculty',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_classroom',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_group',
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups',
                                    to='scheduler.faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    to='scheduler.classroom'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    to='scheduler.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    to='scheduler.date'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    to='scheduler.group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                    to='scheduler.group'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_title',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.URLField(),
        ),
    ]
