# Generated by Django 5.2.9 on 2026-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='half_duration_minutes',
            field=models.PositiveSmallIntegerField(default=45, help_text='Продолжительность одной полупары в минутах (>= 1)'),
        ),
    ]
