# Generated by Django 5.2.9 on 2026-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_timing_half_duration_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='period',
            name='sub_slot',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Полная пара'), (1, '1-я половина'), (2, '2-я половина')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('date', 'lesson_number', 'sub_slot')},
        ),
    ]
