# Generated by Django 5.0.4 on 2024-05-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_course_subject_rename_course_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
    ]
