# Generated by Django 5.0.4 on 2024-05-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_teacher_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
