# Generated by Django 5.2.9 on 2026-05-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_rename_sub_slot_period_part_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_group_i_4b97c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='scheduler_l_period__ee16df_idx',
        ),
        migrations.RemoveIndex(
            model_name='period',
            name='scheduler_p_date_e474d4_idx',
        ),
        # migrations.RenameField(
        #     model_name='timing',
        #     old_name='half_duration_minutes',
        #     new_name='part_duration',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='period',
        #     unique_together={('date', 'lesson_number', 'part')},
        # ),
        # migrations.AddField(
        #     model_name='period',
        #     name='part',
        #     field=models.PositiveSmallIntegerField(choices=[(0, 'full'), (1, '1st part'), (2, '2nd part')], default=0),
        # ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.teacher'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'period'], name='scheduler_l_group_i_0be660_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'period'], name='scheduler_l_teacher_56efa9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['classroom', 'period'], name='scheduler_l_classro_da0640_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['date', 'lesson_number', 'part'], name='scheduler_p_date_324bb3_idx'),
        ),
        # migrations.RemoveField(
        #     model_name='period',
        #     name='sub_slot',
        # ),
    ]
