# Generated by Django 5.0.4 on 2024-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_lesson_date_delete_date'),
    ]

    operations = [

    ]
