# Generated by Django 5.2.9 on 2026-09-05 18:11

import django.db.models.deletion
import scheduler.broadcasts.rules
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_lesson_scheduler_l_group_i_4b97c1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('audience', models.JSONField(default=scheduler.broadcasts.rules.default_audience, validators=[scheduler.broadcasts.rules.validate_audience], verbose_name='Аудитория')),
                ('channel_mode', models.CharField(choices=[('all_available', 'Все доступные каналы'), ('selected', 'Выбранные каналы')], default='all_available', max_length=20, verbose_name='Режим каналов')),
                ('selected_platforms', models.JSONField(blank=True, default=list, validators=[scheduler.broadcasts.rules.validate_platforms], verbose_name='Выбранные каналы')),
                ('resolved_platforms', models.JSONField(blank=True, default=list, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'Ожидает обработки'), ('sending', 'Отправляется'), ('completed', 'Завершена'), ('interrupted', 'Прервана')], db_index=True, default='draft', editable=False, max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('progress_updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('statistics', models.JSONField(blank=True, default=dict, editable=False)),
                ('error', models.TextField(blank=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
                'permissions': [('send_broadcast', 'Can send broadcasts')],
            },
        ),
    ]
