# Generated by Django 5.0.4 on 2024-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_lessontime_lessontimetemplate_alter_classroom_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessontime',
            unique_together={('date', 'lesson_number')},
        ),
        migrations.AlterUniqueTogether(
            name='lessontimetemplate',
            unique_together={('day_of_week', 'lesson_number')},
        ),
    ]
