# Generated by Django 5.0.4 on 2024-05-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_lessontime_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_number',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.lessontime'),
        ),
    ]
