# Generated by Django 5.0.4 on 2024-05-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_remove_lesson_date_remove_lesson_lesson_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subgroup',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='lesson_number',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='lessontime',
            index=models.Index(fields=['date', 'lesson_number'], name='scheduler_l_date_19db36_idx'),
        ),
    ]
