# Generated by Django 5.0.4 on 2024-05-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_remove_lesson_updated_at_lesson_subgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(default='0', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='scheduler_g_is_acti_5ad30c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'lesson_time'], name='scheduler_l_group_i_99f8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='lessontime',
            index=models.Index(fields=['date'], name='scheduler_l_date_db0bea_idx'),
        ),
        migrations.AddField(
            model_name='lessonbuffer',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.classroom'),
        ),
        migrations.AddField(
            model_name='lessonbuffer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.group'),
        ),
        migrations.AddField(
            model_name='lessonbuffer',
            name='lesson_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.lessontime'),
        ),
        migrations.AddField(
            model_name='lessonbuffer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject'),
        ),
        migrations.AddField(
            model_name='lessonbuffer',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'lesson_time'], name='scheduler_l_group_i_74e11c_idx'),
        ),
    ]
