# Generated by Django 5.0.4 on 2024-05-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_lessonbuffer_group_scheduler_g_is_acti_5ad30c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'lesson_time', 'subgroup'], name='scheduler_l_group_i_fb24ce_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbuffer',
            index=models.Index(fields=['group', 'lesson_time', 'subgroup'], name='scheduler_l_group_i_76dd8d_idx'),
        ),
    ]
